// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiii0QJoqAHM_c3nX9z3x5hX_c4jRaXTw',
    appId: '1:798882417625:web:7df7de627383debadfe7c8',
    messagingSenderId: '798882417625',
    projectId: 'ecom-36e16',
    authDomain: 'ecom-36e16.firebaseapp.com',
    storageBucket: 'ecom-36e16.firebasestorage.app',
    measurementId: 'G-ZX5XK7LMN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIb6Lm4reF5YAYpFYFeCn7G0RrkcYHiDM',
    appId: '1:798882417625:android:57e624f529e0388edfe7c8',
    messagingSenderId: '798882417625',
    projectId: 'ecom-36e16',
    storageBucket: 'ecom-36e16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsnazyyX1NBPVMZ27AC2syH8hJ-D0xdpY',
    appId: '1:798882417625:ios:c1fbf1ec95a0ce40dfe7c8',
    messagingSenderId: '798882417625',
    projectId: 'ecom-36e16',
    storageBucket: 'ecom-36e16.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsnazyyX1NBPVMZ27AC2syH8hJ-D0xdpY',
    appId: '1:798882417625:ios:c1fbf1ec95a0ce40dfe7c8',
    messagingSenderId: '798882417625',
    projectId: 'ecom-36e16',
    storageBucket: 'ecom-36e16.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiii0QJoqAHM_c3nX9z3x5hX_c4jRaXTw',
    appId: '1:798882417625:web:a5b99c7e4dfd6d71dfe7c8',
    messagingSenderId: '798882417625',
    projectId: 'ecom-36e16',
    authDomain: 'ecom-36e16.firebaseapp.com',
    storageBucket: 'ecom-36e16.firebasestorage.app',
    measurementId: 'G-9BB7QYZX66',
  );
}
